export default function SafeActionGate({ source, nextStep }) {
  return (
    <section className="safe-action" aria-labelledby="safe-action-title">
      <div className="safe-icon" aria-hidden="true">↗</div>
      <div>
        <p className="eyebrow">Safe next step</p>
        <h2 id="safe-action-title">Check the official source</h2>
        <p>{nextStep}</p>
        {source && (
          <a href={source.url} target="_blank" rel="noreferrer" className="source-link">
            {source.name}<span aria-hidden="true">↗</span>
          </a>
        )}
        {source && <small>{source.reason} Curated official link — never generated by AI.</small>}
      </div>
    </section>
  )
}
